### ISSUE TITLE
入会申込書の「申込日」の元号が平成

### ISSUE THREAD

**Issue by vividtone** [shimane-oss/shimane-oss.github.io#5]
入会申込書 https://www.shimane-oss.org/files/nyukai.pdf の「申込日」の元号が平成になっています。令和か西暦にするのがよいかと思います。

**Comment by kurod1492** [comment]
ご指摘ありがとうございます。「平成」を削除したファイルに更新しました。
#6

**Comment by vividtone** [comment]
早速ご対応ありがとうございました。
